# KFS Configuration

# Weapon Count (Initial)
red_weapon_count: 3 # 红方武器数量
blue_weapon_count: 4 # 蓝方武器数量

inventory:
  num_r1: 3 # R1 KFS数量
  num_r2_true: 4 # R2 KFS数量
  num_fake: 1 # FAKE KFS数量

# Merlin Forest Coordinates (1-12)
meilin:
  red:
    1: [2.2000, 1.8000, 0.7500]
    2: [2.2000, 3.0000, 0.5500]
    3: [2.2000, 4.2000, 0.7500]
    4: [1.0000, 1.8000, 0.9500]
    5: [1.0000, 3.0000, 0.7500]
    6: [1.0000, 4.2000, 0.5500]
    7: [-0.2000, 1.8000, 0.7500]
    8: [-0.2000, 3.0000, 0.9500]
    9: [-0.2000, 4.2000, 0.7500]
    10: [-1.4000, 1.8000, 0.5500]
    11: [-1.4000, 3.0000, 0.7500]
    12: [-1.4000, 4.2000, 0.5500]
  blue:
    1: [2.2000, -4.2000, 0.7500]
    2: [2.2000, -3.0000, 0.5500]
    3: [2.2000, -1.8000, 0.7500]
    4: [1.0000, -4.2000, 0.5500]
    5: [1.0000, -3.0000, 0.7500]
    6: [1.0000, -1.8000, 0.9500]
    7: [-0.2000, -4.2000, 0.7500]
    8: [-0.2000, -3.0000, 0.9500]
    9: [-0.2000, -1.8000, 0.7500]
    10: [-1.4000, -4.2000, 0.5500]
    11: [-1.4000, -3.0000, 0.7500]
    12: [-1.4000, -1.8000, 0.5500]

# 九宫格KFS生成部分参数配置
grid:
  base_x: -4.8 # 九宫格中心基准X坐标 (米)
  base_y: 0.0 # 九宫格中心基准Y坐标 (米)
  base_z_bottom: 1.0 # 底部高度 (米)
  pitch_x: 0.54 # X轴方向间距 (米)
  pitch_z: 0.54 # Z轴方向间距 (米)
  random_range_x: 0.23 # X轴随机偏移范围 (米)
  random_range_y: 0.10 # Y轴随机偏移范围 (米)
  random_range_yaw_deg: 45.0 # Yaw旋转随机范围 (度)



models:
    BlueFakeKFS01: [-9.0, -3.5, -100]
    BlueFakeKFS02: [-9.0, -3.0, -100]
    BlueFakeKFS03: [-9.0, -2.5, -100]
    BlueFakeKFS04: [-9.0, -2.0, -100]
    BlueFakeKFS05: [-9.0, -1.5, -100]
    BlueFakeKFS06: [-9.0, -1.0, -100]
    BlueFakeKFS07: [-9.0, -0.5, -100]
    BlueFakeKFS08: [-9.0, 0.0, -100]
    BlueFakeKFS09: [-9.0, 0.5, -100]
    BlueFakeKFS10: [-9.0, 1.0, -100]
    BlueFakeKFS11: [-9.0, 1.5, -100]
    BlueFakeKFS12: [-9.0, 2.0, -100]
    BlueFakeKFS13: [-9.0, 2.5, -100]
    BlueFakeKFS14: [-9.0, 3.0, -100]
    BlueFakeKFS15: [-9.0, 3.5, -100]

    BlueTrueKFS01: [-8.5, -3.5, -100]
    BlueTrueKFS02: [-8.5, -3.0, -100]
    BlueTrueKFS03: [-8.5, -2.5, -100]
    BlueTrueKFS04: [-8.5, -2.0, -100]
    BlueTrueKFS05: [-8.5, -1.5, -100]
    BlueTrueKFS06: [-8.5, -1.0, -100]
    BlueTrueKFS07: [-8.5, -0.5, -100]
    BlueTrueKFS08: [-8.5, 0.0, -100]
    BlueTrueKFS09: [-8.5, 0.5, -100]
    BlueTrueKFS10: [-8.5, 1.0, -100]
    BlueTrueKFS11: [-8.5, 1.5, -100]
    BlueTrueKFS12: [-8.5, 2.0, -100]
    BlueTrueKFS13: [-8.5, 2.5, -100]
    BlueTrueKFS14: [-8.5, 3.0, -100]
    BlueTrueKFS15: [-8.5, 3.5, -100]
    RedFakeKFS01: [-8.0, -3.5, -100]
    RedFakeKFS02: [-8.0, -3.0, -100]
    RedFakeKFS03: [-8.0, -2.5, -100]
    RedFakeKFS04: [-8.0, -2.0, -100]
    RedFakeKFS05: [-8.0, -1.5, -100]
    RedFakeKFS06: [-8.0, -1.0, -100]
    RedFakeKFS07: [-8.0, -0.5, -100]
    RedFakeKFS08: [-8.0, 0.0, -100]
    RedFakeKFS09: [-8.0, 0.5, -100]
    RedFakeKFS10: [-8.0, 1.0, -100]
    RedFakeKFS11: [-8.0, 1.5, -100]
    RedFakeKFS12: [-8.0, 2.0, -100]
    RedFakeKFS13: [-8.0, 2.5, -100]
    RedFakeKFS14: [-8.0, 3.0, -100]
    RedFakeKFS15: [-8.0, 3.5, -100]

    RedTrueKFS01: [-7.5, -3.5, -100]
    RedTrueKFS02: [-7.5, -3.0, -100]
    RedTrueKFS03: [-7.5, -2.5, -100]
    RedTrueKFS04: [-7.5, -2.0, -100]
    RedTrueKFS05: [-7.5, -1.5, -100]
    RedTrueKFS06: [-7.5, -1.0, -100]
    RedTrueKFS07: [-7.5, -0.5, -100]
    RedTrueKFS08: [-7.5, 0.0, -100]
    RedTrueKFS09: [-7.5, 0.5, -100]
    RedTrueKFS10: [-7.5, 1.0, -100]
    RedTrueKFS11: [-7.5, 1.5, -100]
    RedTrueKFS12: [-7.5, 2.0, -100]
    RedTrueKFS13: [-7.5, 2.5, -100]
    RedTrueKFS14: [-7.5, 3.0, -100]
    RedTrueKFS15: [-7.5, 3.5, -100]
   
    RedR1KFS: [-7.0, -0.5, -100]
    RedR1KFS_2: [-7.0, -0.5, -100]
    RedR1KFS_3: [-7.0, -0.5, -100]
    BlueR1KFS: [-7.0, 0.5, -100]
    BlueR1KFS_2: [-7.0, 0.5, -100]
    BlueR1KFS_3: [-7.0, 0.5, -100]
